# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - "nightly"
    - 3.6
    - 3.5
    - 3.4
    - 3.3
sudo: false
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - GROUP=docs
#group: edge
before_install:
    - 'if [[ $GROUP != js* ]]; then COVERAGE=""; fi'
    - 'if [[ $GROUP == docs ]]; then pip install -r docs/requirements.txt; fi'
install:
    - pip install setuptools pip --upgrade
    - pip install -e file://$PWD#egg=ipython[test] --upgrade
    - pip install codecov --upgrade
script:
    - cd /tmp && iptest --coverage xml && cd -
    - 'if [[ $GROUP == docs ]]; then make -C docs/ html; fi'
after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - codecov

matrix:
    allow_failures:
        - python: nightly
    exclude:
        - python: 2.7
          env: GROUP=docs

before_deploy:
    - rm -rf dist/
    - python setup.py sdist
    - python setup.py bdist_wheel

deploy:
    provider: releases
    api_key:
        secure: Y/Ae9tYs5aoBU8bDjN2YrwGG6tCbezj/h3Lcmtx8HQavSbBgXnhnZVRb2snOKD7auqnqjfT/7QMm4ZyKvaOEgyggGktKqEKYHC8KOZ7yp8I5/UMDtk6j9TnXpSqqBxPiud4MDV76SfRYEQiaDoG4tGGvSfPJ9KcNjKrNvSyyxns=
    file: dist/*
    file_glob: true
    skip_cleanup: true
    on:
        repo: ipython/ipython
        all_branches: true  # Backports are released from e.g. 5.x branch
        tags: true
        python: 3.6  # Any version should work, but we only need one
