# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - "nightly"
    - 3.5
    - 3.4
    - 3.3
    - 2.7
    - pypy
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    - 'if [[ $GROUP != js* ]]; then COVERAGE=""; fi'
install:
    - pip install "setuptools>=18.5"
    - if [ $TRAVIS_PYTHON_VERSION == pypy ] ; then pip install https://bitbucket.org/pypy/numpy/get/pypy-4.0.1.zip ; fi
    - pip install -f travis-wheels/wheelhouse -e file://$PWD#egg=ipython[test]
    - pip install codecov
script:
    - cd /tmp && iptest --coverage xml && cd -
after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - codecov

matrix:
    allow_failures:
        - python: nightly
        - python: pypy
