build: false
matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  matrix:

   - PYTHON: "C:\\Python37-x64"
     PYTHON_VERSION: "3.7.x"
     PYTHON_ARCH: "64"

   - PYTHON: "C:\\Python38"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "32"

   - PYTHON: "C:\\Python38-x64"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade setuptools pip
  - pip install nose coverage pytest
  - pip install .[test]
  - mkdir results
  - cd results
test_script:
  - iptest --coverage xml
on_finish:
  - curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
  - codecov -e PYTHON_VERSION,PYTHON_ARCH
