build: false
matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  matrix:
   - PYTHON: "C:\\Python36"
     PYTHON_VERSION: "3.6.x"
     PYTHON_ARCH: "32"

   - PYTHON: "C:\\Python36-x64"
     PYTHON_VERSION: "3.6.x"
     PYTHON_ARCH: "64"

   - PYTHON: "C:\\Python37"
     PYTHON_VERSION: "3.7.x"
     PYTHON_ARCH: "32"

   - PYTHON: "C:\\Python37-x64"
     PYTHON_VERSION: "3.7.x"
     PYTHON_ARCH: "64"

   - PYTHON: "C:\\Python38"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "32"

   - PYTHON: "C:\\Python38-x64"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: |
      Set-PSDebug -Trace 1
      if ($Env:PYTHON_VERSION.StartsWith("3.8")) {
        if ($Env:PYTHON_ARCH -eq "64") {
          iex "choco install python3 --version=3.8 --no-progress --params /InstallDir:$Env:PYTHON"
        } else {
          iex "choco install python3 --version=3.8 --no-progress --params /InstallDir:$Env:PYTHON --x86"
        }
      }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV%  python -m pip install --upgrade setuptools pip"
  - "%CMD_IN_ENV%  pip install nose coverage"
  - "%CMD_IN_ENV%  pip install .[test]"
  - "%CMD_IN_ENV%  mkdir results"
  - "%CMD_IN_ENV%  cd results"
test_script:
  - "%CMD_IN_ENV%  iptest --coverage xml"
