coverage:
  status:
    patch: off
    project:
      default:
        target: auto
codecov:
  require_ci_to_pass: false

ignore:
  - IPython/kernel/*
  - IPython/consoleapp.py
  - IPython/core/inputsplitter.py
  - IPython/lib/inputhook*.py
  - IPython/lib/kernel.py
  - IPython/utils/jsonutil.py
  - IPython/utils/localinterfaces.py
  - IPython/utils/log.py
  - IPython/utils/signatures.py
  - IPython/utils/traitlets.py
